### ISSUE TITLE
Kérdés

### ISSUE THREAD

**Issue by skyfighteer** [RuzsaGergely/Atlantisz#9]
Van esetleg barmilyen oldal/app ami neptun/kreta replacement es ezt hasznalja?
Egy lista jo lenne

**Comment by RuzsaGergely** [comment]
Tudomásom szerint nincsen olyan projekt ami aktívan használná ezt a rendszert, tekintve, hogy meglehetősen régi és elavult már. Azóta a KRÉTA rendszer mechanizmusa is változott valamennyire, valamint a NEPTUN rendszernek is több része felfedezetlen maradt számomra. 
Egy szó mint száz, mivel ez a projekt maximum inspirációként hat(hatott) néhány emberre mintsem aktív eszközként, így nem igazán tudok vagy lenne értelme listát írnom róla.
